daxp.encoding=UTF-8

# For changes
daxp.contexts.id=1
daxp.contexts.tagPrefix="?"
daxp.contexts.symbol=DFT
daxp.contexts.description=Default application context



# For changes
daxp.appContext.id=1
daxp.appContexts.tagPrefix="?"
daxp.appContexts.symbol=DFT
daxp.appContexts.description=Default application context
