daxp.encoding=UTF8
daxp.application-context-id=1
daxp.new-line-after_block=Y
#
# Context map
daxp.contexts[0].id=0
daxp.contexts[0].tagPrefix=""
daxp.contexts[0].symbol=SYS
daxp.contexts[0].description=Daxp context

# For changes
daxp.contexts[1].id=1
daxp.contexts[1].tagPrefix="?"
daxp.contexts[1].symbol=DFT
daxp.contexts[1].description=Default application context
